The proposal of integrate VLC with RNG
hetu-project/chrono pull request #8
Opened 2024-04-07 11:13 UTC by ivan-xin

Randomness generation based on VRF and VLC
Randomness generation based on BLS and VLC

2024-04-08 05:49 UTC, fshif requested changes
Better to include the respective scenarios in the demo documents.

2024-04-09 12:00 UTC, arunisean commented
@ivan-xin

2024-04-10 11:07 UTC, arunisean approved these changes

2024-04-10 11:22 UTC, fshif approved these changes

2024-04-10 11:23 UTC, merged